name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#18aeab'
    - '#ebebeb'
    - '#226460'
    - '#198d8b'
    - '#4cc5c7'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: follow
    item: null
    url: null
