name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7257
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcb316'
    - '#56352e'
    - '#ffffff'
    - '#de9915'
    - '#fed082'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
