name: null
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#17aba8'
    - '#1f635f'
    - '#198886'
    - '#5ed2d4'
  brandStrength: 0
  lightness: 0
  saturation: 0.6875
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
